# latest qbrocker image
image: $CI_REGISTRY/registry/qb:latest

variables:
  ENTRYPOINT_DEBUG: "0"

test:
  script:
     # force crayon  mode
     - echo "options(crayon.enabled=TRUE)" > .Rprofile
     - make check

     

    
    
    
    


