# latest qbrocker image
image: $CI_REGISTRY/registry/qb:latest

variables:
  ENTRYPOINT_DEBUG: "0"

before_script:
  - echo "options(crayon.enabled=TRUE)" > .Rprofile

coverage:
  script:
    #- make check
    # N.B: colors fool the coverage regexp
    - echo "options(crayon.enabled=FALSE)" > .Rprofile
    - make coverage

check:
  script:
    - make check

pages:
  stage: deploy
  cache:

    paths:
      - lib/
  script:
    # important: generate the roxygen doc prior to run pkgdown
    - make rox
    # install pkgdown in a cached location because it is slow !
    - test -e lib || mkdir lib
    - export R_LIBS=$(pwd)/lib
    # test if pkgdown is installed in lib, otherwise install it
    - Rscript -e 'if (!"pkgdown"  %in% installed.packages()) devtools::install_github("hadley/pkgdown", lib = lib)'
    - cd plinker
    - Rscript -e 'pkgdown::build_site(path = "../public")'

  artifacts:
    paths:
      - public/
